name: Deploy to Production

on:
  release:
    types: [published]

concurrency:
  group: production-deployment
  cancel-in-progress: false

env:
  WORKLOAD_IDENTITY_PROVIDER: projects/${{ vars.GCP_PROJECT_NUMBER_PROD }}/locations/global/workloadIdentityPools/${{ vars.WORKLOAD_IDENTITY_POOL_ID }}/providers/${{ vars.WORKLOAD_IDENTITY_PROVIDER_ID }}
  IMAGE: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID_PROD }}/${{ vars.ARTIFACT_REPO }}/${{ vars.SERVICE_NAME }}:${{ github.event.release.tag_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GIT_SERVICE_ACCOUNT_PROD }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Docker auth
        run: |-
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build -t ${{ env.IMAGE }} .

      - name: Push image
        run: docker push ${{ env.IMAGE }}

      - name: Deploy
        run: |
          gcloud run deploy ${{ vars.SERVICE_NAME }} \
          --image ${{ env.IMAGE }} \
          --region ${{ vars.GCP_REGION }} \
          --port=3000 \
          --service-account=${{ vars.APP_SERVICE_ACCOUNT_PROD }} \
          --memory=512Mi \
          --allow-unauthenticated
